Issue #19: Fetch logged user activities
dragonsbootcampllc/DragonsBootcampLMS pull request #49
Opened 2024-08-09 09:19 UTC by islam01jul00

Now we have more 4 endpoints

GET /api/user/activities => to retrieve authenticated user activities
GET /api/user/activities/:activityId => to retrieve authenticated user activity by id

GET /api/activities => to retrieve all activities
GET /api/activities/:activityId => to retrieve activity by id

2024-08-09 10:47 UTC, zekooo0 approved these changes
LGTM

2024-08-15 14:45 UTC, AhmedNagehAbdelrazek requested changes
the functionality is working fine 
but it would be best if you fixed the other issues

2024-08-15 14:45 UTC, AhmedNagehAbdelrazek commented on Server/Routes/activitiesRoutes.js
> +router.route('/:activityId').get(verifyRole('admin'), getActivity);
the same here too

2024-08-15 14:45 UTC, AhmedNagehAbdelrazek commented on Server/Controllers/userActivitiesController.js
you don't need to create another controller to control the activities, combine both in `activitiesController.js`

2024-08-20 15:50 UTC, AhmedNagehAbdelrazek approved these changes

2024-08-20 15:50 UTC, merged